name: busbro_flutter
description: SG Bus Bro app.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.13.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  http: ^0.13.3
  shared_preferences: ^2.0.7
  location: ^4.2.0
  google_fonts: ^2.3.1
  font_awesome_flutter: ^10.1.0
  provider: ^6.0.3
  get: ^4.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
   - assets/BusDetailsProp.json
   - assets/BusProperties.properties
   - assets/BusSector0.properties
   - assets/BusSector1.properties
   - assets/BusSector2.properties
   - assets/BusSector3.properties
   - assets/BusSector4.properties
   - assets/BusSector5.properties
   - assets/BusSector6.properties
   - assets/BusSector7.properties
   - assets/BusSector8.properties
   - assets/BusSector9.properties
   - assets/BusSector10.properties
   - assets/BusSector11.properties
   - assets/BusSector12.properties
   - assets/BusSector13.properties
   - assets/BusSector14.properties
   - assets/BusSector15.properties
   - assets/BusSector16.properties
   - assets/BusSector17.properties
   - assets/BusSector18.properties
   - assets/BusSector19.properties
   - assets/BusSector20.properties
   - assets/BusSector21.properties
   - assets/BusSector22.properties
   - assets/BusSector23.properties
   - assets/BusSector24.properties
   - assets/BusSector25.properties
   - assets/BusSector26.properties
   - assets/BusSector27.properties
   - assets/BusSector28.properties
   - assets/BusSector29.properties
   - assets/BusSector30.properties
  uses-material-design: true
